//
// Created by Admin on 2020/8/26.
//

#ifndef LEETCODE03_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_SOLUTION_H
#define LEETCODE03_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_SOLUTION_H
#include <string>
using namespace std;
class Solution {
public:
    int lengthOfLongestSubstring(string s);
};


#endif //LEETCODE03_LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_SOLUTION_H
